name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
      - develop
        
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: "–ì—Ä–∏–≥–æ—Ä–∞—à –£.–í"
      GROUP: "M3115"
    steps:
      - name: Information
      - run: |
          echo "–§–ò–û: $NAME"
          echo "–ì—Ä—É–ø–ø–∞: $GROUP"
          echo "–ù–∏–∫: ${{ github.actor }}"
        
      - name: Python installation
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Additional libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Code style check
        run: |
          pip install flake8
          flake8 .
      - name: Testing
        run: pytest
      - name: Formating code
        run: |
          pip install black
          black . #

